#!/bin/sh /etc/rc.common

START=99
STOP=99
USE_PROCD=1
PROG=/usr/bin/lcd1602-daemon

start_service() {
    config_load 'lcd1602'
    local cfg='config'

    local enabled content backlight
    config_get enabled $cfg 'enabled' '1'
    config_get content $cfg 'content' '   BD4SUR OpenWrt                       2025-04-20  01:20:00     ARE YOU OK?    '
    config_get backlight $cfg 'backlight' '1'

    procd_open_instance
    procd_set_param command $PROG
    procd_set_param respawn
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "lcd1602"
}

reload_service() {
    stop "$@"
    start "$@"
}

stop_service() {
    killall $PROG
}
