include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for Nano Language Model Inference
LUCI_DEPENDS:=+luci-base +luci-compat +nano-infer-ws-server
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
