#!/bin/sh /etc/rc.common

START=99
STOP=99
USE_PROCD=1
PROG=/usr/bin/nano-infer-ws-server

start_service() {
    config_load 'nanochat'
    local cfg='config'

    local path max_len port
    config_get path $cfg 'path' '/emmc/_model/nano_168m_625000_sft_947000.bin'
    config_get max_len $cfg 'max_len' '512'
    config_get port $cfg 'port' '8080'

    procd_open_instance
    procd_set_param command $PROG "${path}" -n "${max_len}" -P "${port}"
    procd_set_param respawn
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "nanochat"
}

reload_service() {
    stop "$@"
    start "$@"
}

stop_service() {
    killall $PROG
}
